In [1]:
import os
print(os.path.abspath('.'))

C:\Users\dell


In [1]:
x = torch.tensor(1,requires_grad=True)

NameError: name 'torch' is not defined

In [1]:
import torch

In [2]:
x = torch.tensor(1,requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [3]:
x = torch.tensor(1.0,requires_grad=True)

In [4]:
y = torch.tensor(2.0, requires_grad=True)

In [5]:
z = x**2 + y

In [6]:
z.backward()

In [7]:
print(z, x.grad, y.grad)

tensor(3., grad_fn=<AddBackward0>) tensor(2.) tensor(1.)


In [8]:
x = torch.ones(2, requires_grad =True)

In [9]:
print(x)

tensor([1., 1.], requires_grad=True)


In [10]:
x = torch.tensor([1.0,2.0],requires_grad=True)

In [11]:
print(x)

tensor([1., 2.], requires_grad=True)


In [12]:
z.backward()

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

In [13]:
z = torch.mean(y)

In [14]:
print(z)

tensor(2., grad_fn=<MeanBackward0>)


In [15]:
z.backward()

In [16]:
x.grad

In [17]:
print(x.grad)

None


In [19]:
a = torch.tensor(10.0, requires_grad=True)
b = torch.tensor(20.0, requires_grad=True)

In [20]:
F=a*b

In [21]:
F.backward()

In [22]:
print(a.grad)
print(b.grad)

tensor(20.)
tensor(10.)


In [23]:
a = torch.tensor([10.0,10.0], requires_grad=True)
b = torch.tensor([20.0,20.0], requires_grad=True)

In [24]:
F = a*b

In [25]:
print(F)

tensor([200., 200.], grad_fn=<MulBackward0>)


In [28]:
F.backward(gradient=torch.tensor([1.0,1.0]))

In [29]:
print(a.grad)
print(b.grad)

tensor([20., 20.])
tensor([10., 10.])


In [30]:
a = torch.tensor([10.0,10.0], requires_grad=True)
b = torch.tensor([20.0,20.0], requires_grad=True)
F = a*b
G = 2*F #new

In [32]:
G.backward(gradient=torch.tensor([1.0,1.0]))

In [33]:
print(a.grad, b.grad)

tensor([40., 40.]) tensor([20., 20.])


In [34]:
print(F.grad)

None


D:\AnacondaShengcheng\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.


In [35]:
import torch
x = torch.tensor([1.0,2.0],requires_grad=True)
y = (x + 2)**2

In [36]:
print(y)

tensor([ 9., 16.], grad_fn=<PowBackward0>)


In [41]:
y.backward(torch.tensor([1,1]))
print(x.grad)

tensor([6., 8.])


In [43]:
y = torch.exp(x)
print(y)

tensor([2.7183, 7.3891], grad_fn=<ExpBackward>)


In [44]:
y.backward(torch.tensor([1,1]))

tensor([6., 8.])


In [45]:
y.backward(torch.tensor([1,1]))

In [46]:
print(x.grad)

tensor([ 8.7183, 15.3891])


In [47]:
x = torch.tensor(3.5, requires_grad=True)

In [48]:
y = x**2
z = 2*y + 3

In [49]:
z.backward()

In [50]:
print(x.grad)

tensor(14.)


In [51]:
y.backward()

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

In [52]:
x = torch.tensor(3.5, requires_grad=True)
y = x**2
z = 2*y + 3
y.backward(retain_graph = True)
z.backward()
print(x.grad)
print(y.grad)

tensor(21.)
None


D:\AnacondaShengcheng\lib\site-packages\ipykernel_launcher.py:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  import sys


In [53]:
x = torch.tensor(3.5, requires_grad=True)
y = x**2
z = 2*y + 3
y.backward(retain_graph = True)
z.backward()
print(y.grad)
print(x.grad)


None
tensor(21.)


D:\AnacondaShengcheng\lib\site-packages\ipykernel_launcher.py:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  


In [54]:
x = torch.tensor(3.5, requires_grad=True)
y = x**2
z = 2*y + 3
y.backward(retain_graph = True)

print(y.grad)
z.backward()
print(x.grad)

None
tensor(21.)


D:\AnacondaShengcheng\lib\site-packages\ipykernel_launcher.py:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  


In [55]:
x = torch.tensor(3.5, requires_grad=True)
y = x**2
z = 2*y + 3
y.retain_graph()

print(y.grad)
z.backward()
print(x.grad)

AttributeError: 'Tensor' object has no attribute 'retain_graph'

In [56]:
x = torch.tensor(3.5, requires_grad=True)
y = x**2
z = 2*y + 3
y.retain_grad()

print(y.grad)
z.backward()
print(x.grad)

None
tensor(14.)


In [57]:
x = torch.tensor(2.0, requires_grad=True)

In [58]:
x = 2*a + 3*b
y = 5*a**2 + 3*b**3
z = 2*x + 3*y

In [59]:
z.backward()
print(a.grad())

RuntimeError: grad can be implicitly created only for scalar outputs

In [60]:
z.backward(torch.tensor([1.0,1.0]))
print(a.grad())

TypeError: 'Tensor' object is not callable

In [62]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
x = 2*a + 3*b
y = 5*a**2 + 3*b**3
z = 2*x + 3*y
z.backward()
print(a.grad)

tensor(64.)


In [63]:
print(b.grad)

tensor(33.)
